version: '3.8'

services:
  server:
    build:
      context: .
    ports:
      - 9000:80
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_DATABASE=dockerPhp
      - DB_USERNAME=root
      - DB_PASSWORD=Password!23

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Password!23
      MYSQL_DATABASE: dockerPhp
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  db-data:
